const exercises = [
  {
    id: '6709596b5c61afda0db52e93',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Barbell Bench Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on a flat bench and press a barbell upwards from your chest.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e94',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Squat',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: "Lower your body as if you're sitting back into a chair, then push back up to standing.",
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e95',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Deadlift',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lift a barbell from the ground to hip level, then lower it back down.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e96',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Pull-up',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hang from a bar and pull your body up until your chin is over the bar.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52e97',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Shoulder Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Press dumbbells overhead from shoulder level while seated or standing.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e98',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Leg Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Push a weighted platform away from you using your legs.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e99',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Barbell Row',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Bend over and pull a barbell up to your lower chest.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e9a',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Tricep Pushdown',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Push a cable attachment down using your triceps.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e9b',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Bicep Curl',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Curl dumbbells up towards your shoulders.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e9c',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Lat Pulldown',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Pull a bar down to your upper chest while seated.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e9d',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Leg Extension',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Extend your legs to lift a weighted pad using a machine.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e9e',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Leg Curl',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Curl your legs to lift a weighted pad using a machine.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52e9f',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Lunges',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Step forward into a lunge position while holding dumbbells.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea0',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Calf Raises',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Raise your heels off the ground while standing.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea1',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Incline Bench Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform a bench press on an inclined bench.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea2',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dips',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lower and raise your body between parallel bars.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52ea3',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Face Pull',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Pull a cable attachment towards your face, focusing on rear deltoids.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea4',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Plank',
    type: 'duration',
    'each_side': false,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': 60,
    description: 'Hold a push-up position with your forearms on the ground.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52ea5',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Russian Twist',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Sit with your feet off the ground and twist your torso from side to side.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea6',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Hammer Curl',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Curl dumbbells with a neutral grip (palms facing each other).',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea7',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Seated Cable Row',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Sit at a cable machine and pull the attachment towards your abdomen.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea8',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Overhead Tricep Extension',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hold a dumbbell or barbell overhead and lower it behind your head, then extend your arms.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ea9',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Flyes',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on a bench and open your arms wide with dumbbells, then bring them together above your chest.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eaa',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Lateral Raise',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Stand with dumbbells at your sides, then raise them out to shoulder level.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eab',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Leg Press Calf Raise',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Using a leg press machine, push with your toes to extend your ankles.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eac',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Barbell Hip Thrust',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Rest your upper back on a bench and lift a barbell off the ground using your hips.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ead',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Chest Dips',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lower your body between parallel bars, leaning forward to target the chest.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52eae',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Seated Leg Curl',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Curl your legs to lift a weighted pad while seated on a machine.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eaf',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Row',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Bend over with one hand on a bench, pull a dumbbell up to your side with the other hand.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb0',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Cable Crossover',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Stand between two cable machines and bring the handles together in front of your chest.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb1',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Barbell Shrug',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hold a barbell in front of your thighs and lift your shoulders towards your ears.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb2',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Skull Crushers',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on a bench and lower a barbell or EZ bar to your forehead, then extend your arms.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb3',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Seated Calf Raise',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Sit with your knees bent and raise your heels off the ground using a machine or weights on your thighs.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb4',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Reverse Flyes',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Bend forward at the hips and raise dumbbells out to the sides, focusing on rear deltoids.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb5',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Hanging Leg Raise',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: "Hang from a pull-up bar and raise your legs until they're parallel to the ground.",
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52eb6',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Barbell Curl',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Stand with a barbell in your hands and curl it up towards your shoulders.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb7',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Machine Chest Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Sit at a chest press machine and push the handles away from your chest.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb8',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Romanian Deadlift',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hold a barbell in front of your thighs, hinge at the hips to lower it, keeping legs mostly straight.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eb9',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Seated Shoulder Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Sit on a bench with back support and press dumbbells or a barbell overhead.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52eba',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Preacher Curl',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Rest your arms on a preacher bench and curl a barbell or dumbbells towards your shoulders.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ebb',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Hack Squat',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a hack squat machine to perform a squat motion with your back supported.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ebc',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Decline Bench Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform a bench press on a decline bench to target lower chest muscles.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ebd',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'T-Bar Row',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a T-bar row machine or a barbell in a landmine attachment to perform rows.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ebe',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Arnold Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform a dumbbell shoulder press while rotating your palms from facing you to facing forward.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ebf',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Cable Tricep Kickback',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Using a cable machine, extend your arm backwards to work the triceps.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec0',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Pullover',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on a bench and lower a dumbbell behind your head, then bring it back over your chest.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec1',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Seated Leg Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a seated leg press machine to push the weight away with your legs.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec2',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Front Squat',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform a squat with the barbell racked across the front of your shoulders.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec3',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Upright Row',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lift a barbell or dumbbells vertically in front of your body up to chest level.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec4',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Tricep Extension',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hold a dumbbell with both hands behind your head and extend your arms upward.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec5',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Incline Dumbbell Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on an incline bench and press dumbbells upward from chest level.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec6',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Seated Cable Face Pull',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Sit and pull a cable attachment towards your face, focusing on rear deltoids and upper back.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec7',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Squat',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hold dumbbells at your sides and perform a squat.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec8',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Close-Grip Bench Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform a bench press with hands closer together to target triceps.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ec9',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Reverse Crunch',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on your back and lift your hips off the ground, bringing knees towards chest.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52eca',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Machine Row',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a seated row machine to pull the handles towards your abdomen.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ecb',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Bench Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on a flat bench and press dumbbells upwards from chest level.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ecc',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Glute Bridge',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Lie on your back with knees bent, lift hips upward squeezing glutes.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
  {
    id: '6709596b5c61afda0db52ecd',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Shrug',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Hold dumbbells at your sides and lift your shoulders towards your ears.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ece',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Tricep Rope Pushdown',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a rope attachment on a cable machine to push down and work the triceps.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ecf',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Leg Adduction',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a leg adduction machine to bring your legs together against resistance.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed0',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Leg Abduction',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a leg abduction machine to spread your legs apart against resistance.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed1',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Lateral Lunge',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Hold dumbbells and step to the side, lowering your body into a lunge position.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed2',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Cable Woodchopper',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Pull a cable from high to low in a diagonal chopping motion across your body.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed3',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Barbell Good Morning',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'With a barbell on your shoulders, hinge at the hips to lower your torso parallel to the ground.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed4',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Machine Shoulder Press',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Use a shoulder press machine to push the handles upward.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed5',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Dumbbell Concentration Curl',
    type: 'repeats',
    'each_side': true,
    'hours': false,
    'is_in_workout': false,
    'in_workouts': [],
    'archived': false,
    'image': null,
    'time': null,
    description: 'Sit and curl a dumbbell with your elbow braced against your inner thigh.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed6',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Cable Crunch',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Kneel in front of a cable machine and crunch downward, pulling the cable with your hands behind your head.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed7',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Smith Machine Squat',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform a squat using a Smith machine for guided bar movement.',
    repeats: null,
    weight: null,
    mass_unit: 'kg',
  },
  {
    id: '6709596b5c61afda0db52ed8',
    updated_at: 1648771200000,
    created_at: 1648771200000,
    title: 'Decline Sit-Up',
    type: 'repeats',
    each_side: false,
    hours: false,
    is_in_workout: false,
    in_workouts: [],
    archived: false,
    image: null,
    time: null,
    description: 'Perform sit-ups on a decline bench for increased difficulty.',
    'repeats': null,
    'weight': null,
    'mass_unit': null,
  },
]

export default exercises
