const muscleGroups = [
  {
    title: 'Грудь',
    id: '675e00fc5d1f1d8d19f8e615',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Верхний пучок груди',
    id: '675e00fc5d1f1d8d19f8e616',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Средний пучок груди',
    id: '675e00fc5d1f1d8d19f8e617',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Нижний пучок груди',
    id: '675e00fc5d1f1d8d19f8e618',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Шея',
    id: '675e01da5d1f1d8d19f8e63c',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Ременная мышца',
    id: '675e00fc5d1f1d8d19f8e619',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Боковая мышцы шеи',
    id: '675e00fc5d1f1d8d19f8e61a',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Спина',
    id: '675e00fc5d1f1d8d19f8e61b',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Верхняя Трапецевидная мышца',
    id: '675e00fc5d1f1d8d19f8e61c',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Нижняя Трапецевидная мышца',
    id: '675e00fc5d1f1d8d19f8e61d',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Ромбовидная мышца',
    id: '675e00fc5d1f1d8d19f8e61e',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Широчайшая мышца',
    id: '675e00fc5d1f1d8d19f8e61f',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Выпрямляющая позвоночник мышца',
    id: '675e00fc5d1f1d8d19f8e620',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Квадратная поясничная мышца',
    id: '675e00fc5d1f1d8d19f8e621',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Плечи',
    id: '675e00fc5d1f1d8d19f8e622',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Передняя дельта плеча',
    id: '675e00fc5d1f1d8d19f8e623',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Средняя дельта плеча',
    id: '675e00fc5d1f1d8d19f8e624',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Задняя дельта плеча',
    id: '675e00fc5d1f1d8d19f8e625',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Ноги',
    id: '675e00fc5d1f1d8d19f8e626',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Квадрицепс берда',
    id: '675e00fc5d1f1d8d19f8e627',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Бицепс берда',
    id: '675e00fc5d1f1d8d19f8e628',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Подвздошная мышца',
    id: '675e00fc5d1f1d8d19f8e629',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Прямая мышца бедра',
    id: '675e00fc5d1f1d8d19f8e62a',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Ягодичная мышца',
    id: '675e00fc5d1f1d8d19f8e62b',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Латеральная широкая мышца',
    id: '675e00fc5d1f1d8d19f8e62c',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Медиальная широкая мышца',
    id: '675e00fc5d1f1d8d19f8e62d',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Икроножная мышца',
    id: '675e00fc5d1f1d8d19f8e62e',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Переднаяя большеберцовая мышца',
    id: '675e00fc5d1f1d8d19f8e62f',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Руки',
    id: '675e00fc5d1f1d8d19f8e630',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Трицепс',
    id: '675e00fc5d1f1d8d19f8e631',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Бицепс',
    id: '675e00fc5d1f1d8d19f8e632',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Плечелучевая мышца',
    id: '675e00fc5d1f1d8d19f8e633',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Разгибатель запястья',
    id: '675e00fc5d1f1d8d19f8e634',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Пресс',
    id: '675e00fc5d1f1d8d19f8e635',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Прямая мышца пресса',
    id: '675e00fc5d1f1d8d19f8e636',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Внешние косые мышцы пресса',
    id: '675e00fc5d1f1d8d19f8e637',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Внутренние косые мышцы пресса',
    id: '675e00fc5d1f1d8d19f8e638',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Поперечные мышцы пресса',
    id: '675e00fc5d1f1d8d19f8e639',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Кардио',
    id: '675e00fc5d1f1d8d19f8e63a',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Другое',
    id: '675e00fc5d1f1d8d19f8e63b',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
]

export default muscleGroups
