const muscleGroups = [
  {
    title: 'Chest',
    id: '675e00fc5d1f1d8d19f8e615',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Upper Chest',
    id: '675e00fc5d1f1d8d19f8e616',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Middle Chest',
    id: '675e00fc5d1f1d8d19f8e617',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Lower Chest',
    id: '675e00fc5d1f1d8d19f8e618',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Neck',
    id: '675e01da5d1f1d8d19f8e63c',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Strap Muscle',
    id: '675e00fc5d1f1d8d19f8e619',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Lateral Muscles of the Neck',
    id: '675e00fc5d1f1d8d19f8e61a',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Back',
    id: '675e00fc5d1f1d8d19f8e61b',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Upper Trapezius',
    id: '675e00fc5d1f1d8d19f8e61c',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Lower Trapezius',
    id: '675e00fc5d1f1d8d19f8e61d',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Rhomboid Muscle',
    id: '675e00fc5d1f1d8d19f8e61e',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Latissimus Dorsi',
    id: '675e00fc5d1f1d8d19f8e61f',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Erector Spinae',
    id: '675e00fc5d1f1d8d19f8e620',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Quadratus Lumbar',
    id: '675e00fc5d1f1d8d19f8e621',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Shoulders',
    id: '675e00fc5d1f1d8d19f8e622',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Anterior Deltoid',
    id: '675e00fc5d1f1d8d19f8e623',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Middle Deltoid',
    id: '675e00fc5d1f1d8d19f8e624',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Rear Deltoid',
    id: '675e00fc5d1f1d8d19f8e625',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Legs',
    id: '675e00fc5d1f1d8d19f8e626',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Quadriceps Femur',
    id: '675e00fc5d1f1d8d19f8e627',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Biceps Femur',
    id: '675e00fc5d1f1d8d19f8e628',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Iliacus Muscle',
    id: '675e00fc5d1f1d8d19f8e629',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Rectus Femur',
    id: '675e00fc5d1f1d8d19f8e62a',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Gluteus Muscle',
    id: '675e00fc5d1f1d8d19f8e62b',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Lateral Vastus Muscle',
    id: '675e00fc5d1f1d8d19f8e62c',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Medial broad muscle',
    id: '675e00fc5d1f1d8d19f8e62d',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Gastrocnemius muscle',
    id: '675e00fc5d1f1d8d19f8e62e',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Anterior tibial muscle',
    id: '675e00fc5d1f1d8d19f8e62f',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Arms',
    id: '675e00fc5d1f1d8d19f8e630',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Triceps',
    id: '675e00fc5d1f1d8d19f8e631',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Biceps',
    id: '675e00fc5d1f1d8d19f8e632',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Brachiradialis muscle',
    id: '675e00fc5d1f1d8d19f8e633',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Extensor carpi',
    id: '675e00fc5d1f1d8d19f8e634',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Abs',
    id: '675e00fc5d1f1d8d19f8e635',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Rectus abdominis muscle',
    id: '675e00fc5d1f1d8d19f8e636',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'External obliques',
    id: '675e00fc5d1f1d8d19f8e637',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Internal obliques',
    id: '675e00fc5d1f1d8d19f8e638',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Transverse abdominal muscles',
    id: '675e00fc5d1f1d8d19f8e639',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Cardio',
    id: '675e00fc5d1f1d8d19f8e63a',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
  {
    title: 'Other',
    id: '675e00fc5d1f1d8d19f8e63b',
    in_exercises: [],
    is_in_exercise: false,
    created_at: 0,
    updated_at: 0,
    is_default: true,
  },
]

export default muscleGroups
